### ISSUE TITLE
Error: Job 'Check Spelling' failed

### ISSUE THREAD

**Issue by Surya-smart619** [check-spelling/spell-check-this#2]
I was trying to run [check-spelling action](https://github.com/marketplace/actions/check-spelling) with [act](https://github.com/nektos/act#installation) locally. 

Yaml file I used
**/.github/workflows/spelling.yml**
```
name: Check Spelling

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request_target:
  issue_comment:
    types: [created]

jobs:

  spelling:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: read
      actions: read
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
    - name: check-spelling
      id: spelling
      uses: check-spelling/check-spelling@main
      with:
        suppress_push_for_open_pull_request: 1
        checkout: true
        spell_check_this: check-spelling/spell-check-this@prerelease
        post_comment: 0
        experimental_apply_changes_via_bot: 1
```

**Actual output I got:**
![image](https://user-images.githubusercontent.com/54700181/199279019-4684ba0d-5e4e-474a-9af4-ff48ae21e34f.png)

I couldn't find what the exact issue was. Please help me to resolve this.
